[package]
name = "packadvice"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.30"
tokio = { version = "1.18.5", features = ["fs", "io-util", "rt-multi-thread"] }
serde_json = "1.0.78"
async-recursion = "1.0.0"
