name: Build
on:
  push: {}
env:
  CARGO_TERM_COLOR: always
jobs:
  linux-x64-gnu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: 'PackAdvice executable (Linux, x64)'
          path: target/release/packadvice
  windows-x64-gnu:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: 'PackAdvice executable (Windows, x64)'
          path: target/release/packadvice.exe
  macos-x64-darwin:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: 'PackAdvice executable (MacOS, x64)'
          path: target/release/packadvice