name: Build
on:
  push: {}
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    strategy:
      matrix:
        name:
          - Linux, x64
          - Windows x64
          - MacOS, x64
        include:
          - name: Linux, x64
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            app-name: packadvice
          - name: Windows x64
            target: x86_64-pc-windows-msvc
            os: windows-latest
            app-name: packadvice.exe
          - name: MacOS, x64
            target: x86_64-apple-darwin
            os: macos-latest
            app-name: packadvice
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=${{ matrix.target }}
      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: PackAdvice executable (${{ matrix.name }})
          path: target/${{ matrix.target }}/release/${{ matrix.app-name }}