cargo-features = ["different-binary-name"]

[package]
name = "packadvice-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "packadvice-cli"
filename = "packadvice"

[dependencies]
packadvice = { path = "../packadvice" }
getopts = "0.2"
